// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<AppInfo> appInfo() => RustLib.instance.api.crateApiAppInfo();

Future<HealthStatus> health() => RustLib.instance.api.crateApiHealth();

Future<List<Capability>> capabilities() =>
    RustLib.instance.api.crateApiCapabilities();

class AppInfo {
  final String name;
  final String version;
  final int coreApiVersion;

  const AppInfo({
    required this.name,
    required this.version,
    required this.coreApiVersion,
  });

  @override
  int get hashCode =>
      name.hashCode ^ version.hashCode ^ coreApiVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version &&
          coreApiVersion == other.coreApiVersion;
}

class Capability {
  final String id;
  final int version;

  const Capability({required this.id, required this.version});

  @override
  int get hashCode => id.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Capability &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          version == other.version;
}

class HealthStatus {
  final String status;

  const HealthStatus({required this.status});

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthStatus &&
          runtimeType == other.runtimeType &&
          status == other.status;
}
