// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/project.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ProjectHostHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandlePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ProjectHostHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    dynamic raw,
  );

  @protected
  ProjectHostHandle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    dynamic raw,
  );

  @protected
  ProjectHostHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    dynamic raw,
  );

  @protected
  ProjectHostHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<MediaArtifactEventView>
  dco_decode_StreamSink_media_artifact_event_view_Sse(dynamic raw);

  @protected
  RustStreamSink<ProjectHostEventView>
  dco_decode_StreamSink_project_host_event_view_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppInfo dco_decode_app_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MediaArtifactBytesView dco_decode_box_autoadd_media_artifact_bytes_view(
    dynamic raw,
  );

  @protected
  ProjectTimelineTrackStateView
  dco_decode_box_autoadd_project_timeline_track_state_view(dynamic raw);

  @protected
  ProjectTimelineVisualSettingsView
  dco_decode_box_autoadd_project_timeline_visual_settings_view(dynamic raw);

  @protected
  ProjectView dco_decode_box_autoadd_project_view(dynamic raw);

  @protected
  RationalRateView dco_decode_box_autoadd_rational_rate_view(dynamic raw);

  @protected
  RationalTimeView dco_decode_box_autoadd_rational_time_view(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  Capability dco_decode_capability(dynamic raw);

  @protected
  HealthStatus dco_decode_health_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Capability> dco_decode_list_capability(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectMediaItemView> dco_decode_list_project_media_item_view(
    dynamic raw,
  );

  @protected
  List<ProjectTimelineClipView> dco_decode_list_project_timeline_clip_view(
    dynamic raw,
  );

  @protected
  List<ProjectTimelineMarkerView> dco_decode_list_project_timeline_marker_view(
    dynamic raw,
  );

  @protected
  List<ProjectTimelineTrackView> dco_decode_list_project_timeline_track_view(
    dynamic raw,
  );

  @protected
  MediaArtifactBytesView dco_decode_media_artifact_bytes_view(dynamic raw);

  @protected
  MediaArtifactEventStateView dco_decode_media_artifact_event_state_view(
    dynamic raw,
  );

  @protected
  MediaArtifactEventView dco_decode_media_artifact_event_view(dynamic raw);

  @protected
  MediaArtifactKindView dco_decode_media_artifact_kind_view(dynamic raw);

  @protected
  MediaArtifactRequestStateView dco_decode_media_artifact_request_state_view(
    dynamic raw,
  );

  @protected
  MediaArtifactRequestView dco_decode_media_artifact_request_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MediaArtifactBytesView? dco_decode_opt_box_autoadd_media_artifact_bytes_view(
    dynamic raw,
  );

  @protected
  ProjectView? dco_decode_opt_box_autoadd_project_view(dynamic raw);

  @protected
  RationalRateView? dco_decode_opt_box_autoadd_rational_rate_view(dynamic raw);

  @protected
  RationalTimeView? dco_decode_opt_box_autoadd_rational_time_view(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PreviewFrameStepView dco_decode_preview_frame_step_view(dynamic raw);

  @protected
  ProjectActionResult dco_decode_project_action_result(dynamic raw);

  @protected
  ProjectBridgeError dco_decode_project_bridge_error(dynamic raw);

  @protected
  ProjectHostEventView dco_decode_project_host_event_view(dynamic raw);

  @protected
  ProjectMediaItemView dco_decode_project_media_item_view(dynamic raw);

  @protected
  ProjectMediaPageView dco_decode_project_media_page_view(dynamic raw);

  @protected
  ProjectPreviewStateView dco_decode_project_preview_state_view(dynamic raw);

  @protected
  ProjectTimelineClipPageView dco_decode_project_timeline_clip_page_view(
    dynamic raw,
  );

  @protected
  ProjectTimelineClipView dco_decode_project_timeline_clip_view(dynamic raw);

  @protected
  ProjectTimelineMarkerPageView dco_decode_project_timeline_marker_page_view(
    dynamic raw,
  );

  @protected
  ProjectTimelineMarkerView dco_decode_project_timeline_marker_view(
    dynamic raw,
  );

  @protected
  ProjectTimelineSequenceSettingsView
  dco_decode_project_timeline_sequence_settings_view(dynamic raw);

  @protected
  ProjectTimelineSnapView dco_decode_project_timeline_snap_view(dynamic raw);

  @protected
  ProjectTimelineTrackStateView dco_decode_project_timeline_track_state_view(
    dynamic raw,
  );

  @protected
  ProjectTimelineTrackView dco_decode_project_timeline_track_view(dynamic raw);

  @protected
  ProjectTimelineTracksView dco_decode_project_timeline_tracks_view(
    dynamic raw,
  );

  @protected
  ProjectTimelineVisualSettingsView
  dco_decode_project_timeline_visual_settings_view(dynamic raw);

  @protected
  ProjectView dco_decode_project_view(dynamic raw);

  @protected
  RationalRateView dco_decode_rational_rate_view(dynamic raw);

  @protected
  RationalTimeView dco_decode_rational_time_view(dynamic raw);

  @protected
  RecoveryActionResult dco_decode_recovery_action_result(dynamic raw);

  @protected
  RecoveryInspectionView dco_decode_recovery_inspection_view(dynamic raw);

  @protected
  TimelineSnapMovingAnchorView dco_decode_timeline_snap_moving_anchor_view(
    dynamic raw,
  );

  @protected
  TimelineSnapOperationView dco_decode_timeline_snap_operation_view(
    dynamic raw,
  );

  @protected
  TimelineSnapTargetKindView dco_decode_timeline_snap_target_kind_view(
    dynamic raw,
  );

  @protected
  TimelineTrackKindView dco_decode_timeline_track_kind_view(dynamic raw);

  @protected
  TimelineTrimEdgeView dco_decode_timeline_trim_edge_view(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ProjectHostHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    SseDeserializer deserializer,
  );

  @protected
  ProjectHostHandle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    SseDeserializer deserializer,
  );

  @protected
  ProjectHostHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    SseDeserializer deserializer,
  );

  @protected
  ProjectHostHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MediaArtifactEventView>
  sse_decode_StreamSink_media_artifact_event_view_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProjectHostEventView>
  sse_decode_StreamSink_project_host_event_view_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MediaArtifactBytesView sse_decode_box_autoadd_media_artifact_bytes_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineTrackStateView
  sse_decode_box_autoadd_project_timeline_track_state_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineVisualSettingsView
  sse_decode_box_autoadd_project_timeline_visual_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectView sse_decode_box_autoadd_project_view(SseDeserializer deserializer);

  @protected
  RationalRateView sse_decode_box_autoadd_rational_rate_view(
    SseDeserializer deserializer,
  );

  @protected
  RationalTimeView sse_decode_box_autoadd_rational_time_view(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Capability sse_decode_capability(SseDeserializer deserializer);

  @protected
  HealthStatus sse_decode_health_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Capability> sse_decode_list_capability(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectMediaItemView> sse_decode_list_project_media_item_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ProjectTimelineClipView> sse_decode_list_project_timeline_clip_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ProjectTimelineMarkerView> sse_decode_list_project_timeline_marker_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ProjectTimelineTrackView> sse_decode_list_project_timeline_track_view(
    SseDeserializer deserializer,
  );

  @protected
  MediaArtifactBytesView sse_decode_media_artifact_bytes_view(
    SseDeserializer deserializer,
  );

  @protected
  MediaArtifactEventStateView sse_decode_media_artifact_event_state_view(
    SseDeserializer deserializer,
  );

  @protected
  MediaArtifactEventView sse_decode_media_artifact_event_view(
    SseDeserializer deserializer,
  );

  @protected
  MediaArtifactKindView sse_decode_media_artifact_kind_view(
    SseDeserializer deserializer,
  );

  @protected
  MediaArtifactRequestStateView sse_decode_media_artifact_request_state_view(
    SseDeserializer deserializer,
  );

  @protected
  MediaArtifactRequestView sse_decode_media_artifact_request_view(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MediaArtifactBytesView? sse_decode_opt_box_autoadd_media_artifact_bytes_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectView? sse_decode_opt_box_autoadd_project_view(
    SseDeserializer deserializer,
  );

  @protected
  RationalRateView? sse_decode_opt_box_autoadd_rational_rate_view(
    SseDeserializer deserializer,
  );

  @protected
  RationalTimeView? sse_decode_opt_box_autoadd_rational_time_view(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PreviewFrameStepView sse_decode_preview_frame_step_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectActionResult sse_decode_project_action_result(
    SseDeserializer deserializer,
  );

  @protected
  ProjectBridgeError sse_decode_project_bridge_error(
    SseDeserializer deserializer,
  );

  @protected
  ProjectHostEventView sse_decode_project_host_event_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectMediaItemView sse_decode_project_media_item_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectMediaPageView sse_decode_project_media_page_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectPreviewStateView sse_decode_project_preview_state_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineClipPageView sse_decode_project_timeline_clip_page_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineClipView sse_decode_project_timeline_clip_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineMarkerPageView sse_decode_project_timeline_marker_page_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineMarkerView sse_decode_project_timeline_marker_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineSequenceSettingsView
  sse_decode_project_timeline_sequence_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineSnapView sse_decode_project_timeline_snap_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineTrackStateView sse_decode_project_timeline_track_state_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineTrackView sse_decode_project_timeline_track_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineTracksView sse_decode_project_timeline_tracks_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectTimelineVisualSettingsView
  sse_decode_project_timeline_visual_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  ProjectView sse_decode_project_view(SseDeserializer deserializer);

  @protected
  RationalRateView sse_decode_rational_rate_view(SseDeserializer deserializer);

  @protected
  RationalTimeView sse_decode_rational_time_view(SseDeserializer deserializer);

  @protected
  RecoveryActionResult sse_decode_recovery_action_result(
    SseDeserializer deserializer,
  );

  @protected
  RecoveryInspectionView sse_decode_recovery_inspection_view(
    SseDeserializer deserializer,
  );

  @protected
  TimelineSnapMovingAnchorView sse_decode_timeline_snap_moving_anchor_view(
    SseDeserializer deserializer,
  );

  @protected
  TimelineSnapOperationView sse_decode_timeline_snap_operation_view(
    SseDeserializer deserializer,
  );

  @protected
  TimelineSnapTargetKindView sse_decode_timeline_snap_target_kind_view(
    SseDeserializer deserializer,
  );

  @protected
  TimelineTrackKindView sse_decode_timeline_track_kind_view(
    SseDeserializer deserializer,
  );

  @protected
  TimelineTrimEdgeView sse_decode_timeline_trim_edge_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    ProjectHostHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    ProjectHostHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    ProjectHostHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    ProjectHostHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_media_artifact_event_view_Sse(
    RustStreamSink<MediaArtifactEventView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_project_host_event_view_Sse(
    RustStreamSink<ProjectHostEventView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_artifact_bytes_view(
    MediaArtifactBytesView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_project_timeline_track_state_view(
    ProjectTimelineTrackStateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_project_timeline_visual_settings_view(
    ProjectTimelineVisualSettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_project_view(
    ProjectView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rational_rate_view(
    RationalRateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rational_time_view(
    RationalTimeView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_capability(Capability self, SseSerializer serializer);

  @protected
  void sse_encode_health_status(HealthStatus self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_capability(
    List<Capability> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_media_item_view(
    List<ProjectMediaItemView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_timeline_clip_view(
    List<ProjectTimelineClipView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_timeline_marker_view(
    List<ProjectTimelineMarkerView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_timeline_track_view(
    List<ProjectTimelineTrackView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_artifact_bytes_view(
    MediaArtifactBytesView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_artifact_event_state_view(
    MediaArtifactEventStateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_artifact_event_view(
    MediaArtifactEventView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_artifact_kind_view(
    MediaArtifactKindView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_artifact_request_state_view(
    MediaArtifactRequestStateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_artifact_request_view(
    MediaArtifactRequestView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_artifact_bytes_view(
    MediaArtifactBytesView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_project_view(
    ProjectView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rational_rate_view(
    RationalRateView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rational_time_view(
    RationalTimeView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_preview_frame_step_view(
    PreviewFrameStepView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_action_result(
    ProjectActionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_bridge_error(
    ProjectBridgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_host_event_view(
    ProjectHostEventView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_media_item_view(
    ProjectMediaItemView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_media_page_view(
    ProjectMediaPageView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_preview_state_view(
    ProjectPreviewStateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_clip_page_view(
    ProjectTimelineClipPageView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_clip_view(
    ProjectTimelineClipView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_marker_page_view(
    ProjectTimelineMarkerPageView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_marker_view(
    ProjectTimelineMarkerView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_sequence_settings_view(
    ProjectTimelineSequenceSettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_snap_view(
    ProjectTimelineSnapView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_track_state_view(
    ProjectTimelineTrackStateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_track_view(
    ProjectTimelineTrackView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_tracks_view(
    ProjectTimelineTracksView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_timeline_visual_settings_view(
    ProjectTimelineVisualSettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_view(ProjectView self, SseSerializer serializer);

  @protected
  void sse_encode_rational_rate_view(
    RationalRateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rational_time_view(
    RationalTimeView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_action_result(
    RecoveryActionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_inspection_view(
    RecoveryInspectionView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_snap_moving_anchor_view(
    TimelineSnapMovingAnchorView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_snap_operation_view(
    TimelineSnapOperationView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_snap_target_kind_view(
    TimelineSnapTargetKindView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_track_kind_view(
    TimelineTrackKindView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_trim_edge_view(
    TimelineTrimEdgeView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_or_app_bridge_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_or_app_bridge_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProjectHostHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
