// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `action_error`, `action_operation_error`, `cache_artifact_kind`, `cache_unavailable_error`, `command`, `configured_media_artifact_cache_root`, `create_media_artifact_service`, `dispatch_command`, `event_view`, `failed`, `forward_events`, `forward_media_artifact_events`, `from_request`, `host_error`, `invalid_arguments`, `invalid_timeline_id`, `media_artifact_cache_root`, `media_artifact_event_view`, `media_item_view`, `non_empty_environment_path`, `operation_bridge_error`, `operation_error_code`, `parse_session_identity`, `project_session_error`, `project_view`, `query`, `rational_time_view`, `recovery_action_error`, `recovery_conflict_name`, `request_media_artifact`, `start_project_host`, `timeline_arguments_error`, `timeline_clip_page_view`, `timeline_clip_view`, `timeline_command`, `timeline_query_arguments_error`, `timeline_track_view`, `unexpected_response_error`, `view_from_query`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachePlatform`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ProjectHostHandle> createProject({
  required String path,
  required String name,
}) => RustLib.instance.api.crateApiProjectCreateProject(path: path, name: name);

Future<ProjectHostHandle> openProject({required String path}) =>
    RustLib.instance.api.crateApiProjectOpenProject(path: path);

Future<RecoveryInspectionView> inspectRecovery({required String path}) =>
    RustLib.instance.api.crateApiProjectInspectRecovery(path: path);

Future<RecoveryActionResult> applyRecovery({required String path}) =>
    RustLib.instance.api.crateApiProjectApplyRecovery(path: path);

Future<RecoveryActionResult> discardRecovery({required String path}) =>
    RustLib.instance.api.crateApiProjectDiscardRecovery(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProjectHostHandle>>
abstract class ProjectHostHandle implements RustOpaqueInterface {
  Future<ProjectActionResult> addTimelineTrack({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required TimelineTrackKindView kind,
  });

  Future<ProjectActionResult> close({required bool discardUnsaved});

  Future<ProjectActionResult> deleteTimelineClip({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String clipId,
  });

  /// Prepares media without holding the live-host lock, then dispatches with the
  /// identity and revision captured by the caller before probing started.
  Future<ProjectActionResult> importMedia({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String path,
  });

  Future<ProjectActionResult> insertTimelineClip({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String trackId,
    required String mediaId,
    required PlatformInt64 timelineStartNumerator,
    required int timelineStartDenominator,
    required PlatformInt64 sourceStartNumerator,
    required int sourceStartDenominator,
    required PlatformInt64 durationNumerator,
    required int durationDenominator,
  });

  Future<ProjectMediaPageView> listMediaPage({
    required BigInt offset,
    required BigInt limit,
  });

  Future<ProjectTimelineClipPageView> listTimelineClips({
    required String trackId,
    required BigInt offset,
    required BigInt limit,
  });

  Future<ProjectTimelineTracksView> listTimelineTracks();

  Future<ProjectActionResult> moveTimelineClip({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String clipId,
    required String trackId,
    required PlatformInt64 timelineStartNumerator,
    required int timelineStartDenominator,
  });

  Future<MediaArtifactBytesView?> readMediaArtifact({
    required MediaArtifactKindView kind,
    required String cacheKey,
  });

  Future<ProjectActionResult> redo({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
  });

  Future<ProjectActionResult> removeMedia({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String mediaId,
  });

  Future<ProjectActionResult> removeTimelineTrack({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String trackId,
  });

  Future<ProjectActionResult> rename({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String name,
  });

  Future<MediaArtifactRequestView> requestMediaThumbnail({
    required String mediaId,
  });

  Future<MediaArtifactRequestView> requestMediaWaveform({
    required String mediaId,
  });

  Future<ProjectActionResult> rippleDeleteTimelineClip({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String clipId,
  });

  Future<ProjectActionResult> save();

  Future<ProjectActionResult> splitTimelineClip({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String clipId,
    required PlatformInt64 timelineTimeNumerator,
    required int timelineTimeDenominator,
  });

  Stream<ProjectHostEventView> subscribeEvents();

  Stream<MediaArtifactEventView> subscribeMediaArtifactEvents();

  Future<ProjectView> summary();

  Future<ProjectActionResult> trimTimelineClip({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
    required String clipId,
    required TimelineTrimEdgeView edge,
    required PlatformInt64 timelineTimeNumerator,
    required int timelineTimeDenominator,
  });

  Future<ProjectActionResult> undo({
    required String projectId,
    required String projectInstanceId,
    required BigInt expectedRevision,
  });
}

class MediaArtifactBytesView {
  final Uint8List bytes;
  final String mimeType;

  const MediaArtifactBytesView({required this.bytes, required this.mimeType});

  @override
  int get hashCode => bytes.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaArtifactBytesView &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          mimeType == other.mimeType;
}

enum MediaArtifactEventStateView { succeeded, failed, cancelled }

class MediaArtifactEventView {
  final BigInt sequence;
  final String mediaId;
  final MediaArtifactKindView kind;
  final String cacheKey;
  final String jobId;
  final MediaArtifactEventStateView state;
  final String? errorCode;

  const MediaArtifactEventView({
    required this.sequence,
    required this.mediaId,
    required this.kind,
    required this.cacheKey,
    required this.jobId,
    required this.state,
    this.errorCode,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^
      mediaId.hashCode ^
      kind.hashCode ^
      cacheKey.hashCode ^
      jobId.hashCode ^
      state.hashCode ^
      errorCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaArtifactEventView &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          mediaId == other.mediaId &&
          kind == other.kind &&
          cacheKey == other.cacheKey &&
          jobId == other.jobId &&
          state == other.state &&
          errorCode == other.errorCode;
}

enum MediaArtifactKindView { thumbnail, waveform }

enum MediaArtifactRequestStateView {
  ready,
  queued,
  running,
  notApplicable,
  failed,
}

class MediaArtifactRequestView {
  final String mediaId;
  final MediaArtifactKindView kind;
  final String? cacheKey;
  final String? jobId;
  final MediaArtifactRequestStateView state;
  final String? errorCode;
  final String? message;

  const MediaArtifactRequestView({
    required this.mediaId,
    required this.kind,
    this.cacheKey,
    this.jobId,
    required this.state,
    this.errorCode,
    this.message,
  });

  @override
  int get hashCode =>
      mediaId.hashCode ^
      kind.hashCode ^
      cacheKey.hashCode ^
      jobId.hashCode ^
      state.hashCode ^
      errorCode.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaArtifactRequestView &&
          runtimeType == other.runtimeType &&
          mediaId == other.mediaId &&
          kind == other.kind &&
          cacheKey == other.cacheKey &&
          jobId == other.jobId &&
          state == other.state &&
          errorCode == other.errorCode &&
          message == other.message;
}

class ProjectActionResult {
  final bool succeeded;
  final String errorCode;
  final String message;
  final ProjectView? view;

  const ProjectActionResult({
    required this.succeeded,
    required this.errorCode,
    required this.message,
    this.view,
  });

  @override
  int get hashCode =>
      succeeded.hashCode ^
      errorCode.hashCode ^
      message.hashCode ^
      view.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectActionResult &&
          runtimeType == other.runtimeType &&
          succeeded == other.succeeded &&
          errorCode == other.errorCode &&
          message == other.message &&
          view == other.view;
}

class ProjectBridgeError implements FrbException {
  final String code;
  final String message;

  const ProjectBridgeError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectBridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class ProjectHostEventView {
  final BigInt sequence;
  final String kind;
  final String projectId;
  final String projectInstanceId;
  final BigInt revision;
  final bool dirty;

  const ProjectHostEventView({
    required this.sequence,
    required this.kind,
    required this.projectId,
    required this.projectInstanceId,
    required this.revision,
    required this.dirty,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^
      kind.hashCode ^
      projectId.hashCode ^
      projectInstanceId.hashCode ^
      revision.hashCode ^
      dirty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectHostEventView &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          kind == other.kind &&
          projectId == other.projectId &&
          projectInstanceId == other.projectInstanceId &&
          revision == other.revision &&
          dirty == other.dirty;
}

class ProjectMediaItemView {
  final String mediaId;
  final String sourceUri;
  final List<String> formatNames;
  final String? duration;
  final String? videoDetails;
  final String? audioDetails;
  final RationalTimeView? containerDuration;
  final RationalTimeView? firstVideoDuration;
  final RationalTimeView? firstAudioDuration;

  const ProjectMediaItemView({
    required this.mediaId,
    required this.sourceUri,
    required this.formatNames,
    this.duration,
    this.videoDetails,
    this.audioDetails,
    this.containerDuration,
    this.firstVideoDuration,
    this.firstAudioDuration,
  });

  @override
  int get hashCode =>
      mediaId.hashCode ^
      sourceUri.hashCode ^
      formatNames.hashCode ^
      duration.hashCode ^
      videoDetails.hashCode ^
      audioDetails.hashCode ^
      containerDuration.hashCode ^
      firstVideoDuration.hashCode ^
      firstAudioDuration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectMediaItemView &&
          runtimeType == other.runtimeType &&
          mediaId == other.mediaId &&
          sourceUri == other.sourceUri &&
          formatNames == other.formatNames &&
          duration == other.duration &&
          videoDetails == other.videoDetails &&
          audioDetails == other.audioDetails &&
          containerDuration == other.containerDuration &&
          firstVideoDuration == other.firstVideoDuration &&
          firstAudioDuration == other.firstAudioDuration;
}

class ProjectMediaPageView {
  final String projectId;
  final String projectInstanceId;
  final BigInt projectRevision;
  final List<ProjectMediaItemView> items;
  final BigInt totalCount;
  final BigInt offset;
  final BigInt limit;
  final BigInt? nextOffset;

  const ProjectMediaPageView({
    required this.projectId,
    required this.projectInstanceId,
    required this.projectRevision,
    required this.items,
    required this.totalCount,
    required this.offset,
    required this.limit,
    this.nextOffset,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectInstanceId.hashCode ^
      projectRevision.hashCode ^
      items.hashCode ^
      totalCount.hashCode ^
      offset.hashCode ^
      limit.hashCode ^
      nextOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectMediaPageView &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectInstanceId == other.projectInstanceId &&
          projectRevision == other.projectRevision &&
          items == other.items &&
          totalCount == other.totalCount &&
          offset == other.offset &&
          limit == other.limit &&
          nextOffset == other.nextOffset;
}

class ProjectTimelineClipPageView {
  final String projectId;
  final String projectInstanceId;
  final BigInt projectRevision;
  final String trackId;
  final List<ProjectTimelineClipView> items;
  final BigInt totalCount;
  final BigInt offset;
  final BigInt limit;
  final BigInt? nextOffset;

  const ProjectTimelineClipPageView({
    required this.projectId,
    required this.projectInstanceId,
    required this.projectRevision,
    required this.trackId,
    required this.items,
    required this.totalCount,
    required this.offset,
    required this.limit,
    this.nextOffset,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectInstanceId.hashCode ^
      projectRevision.hashCode ^
      trackId.hashCode ^
      items.hashCode ^
      totalCount.hashCode ^
      offset.hashCode ^
      limit.hashCode ^
      nextOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectTimelineClipPageView &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectInstanceId == other.projectInstanceId &&
          projectRevision == other.projectRevision &&
          trackId == other.trackId &&
          items == other.items &&
          totalCount == other.totalCount &&
          offset == other.offset &&
          limit == other.limit &&
          nextOffset == other.nextOffset;
}

class ProjectTimelineClipView {
  final String clipId;
  final String mediaId;
  final RationalTimeView timelineStart;
  final RationalTimeView sourceStart;
  final RationalTimeView sourceDuration;

  const ProjectTimelineClipView({
    required this.clipId,
    required this.mediaId,
    required this.timelineStart,
    required this.sourceStart,
    required this.sourceDuration,
  });

  @override
  int get hashCode =>
      clipId.hashCode ^
      mediaId.hashCode ^
      timelineStart.hashCode ^
      sourceStart.hashCode ^
      sourceDuration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectTimelineClipView &&
          runtimeType == other.runtimeType &&
          clipId == other.clipId &&
          mediaId == other.mediaId &&
          timelineStart == other.timelineStart &&
          sourceStart == other.sourceStart &&
          sourceDuration == other.sourceDuration;
}

class ProjectTimelineTrackView {
  final String trackId;
  final TimelineTrackKindView kind;
  final BigInt clipCount;

  const ProjectTimelineTrackView({
    required this.trackId,
    required this.kind,
    required this.clipCount,
  });

  @override
  int get hashCode => trackId.hashCode ^ kind.hashCode ^ clipCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectTimelineTrackView &&
          runtimeType == other.runtimeType &&
          trackId == other.trackId &&
          kind == other.kind &&
          clipCount == other.clipCount;
}

class ProjectTimelineTracksView {
  final String projectId;
  final String projectInstanceId;
  final BigInt projectRevision;
  final List<ProjectTimelineTrackView> items;

  const ProjectTimelineTracksView({
    required this.projectId,
    required this.projectInstanceId,
    required this.projectRevision,
    required this.items,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectInstanceId.hashCode ^
      projectRevision.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectTimelineTracksView &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectInstanceId == other.projectInstanceId &&
          projectRevision == other.projectRevision &&
          items == other.items;
}

class ProjectView {
  final String projectId;
  final String projectInstanceId;
  final BigInt revision;
  final String name;
  final bool dirty;
  final String descriptorPath;

  const ProjectView({
    required this.projectId,
    required this.projectInstanceId,
    required this.revision,
    required this.name,
    required this.dirty,
    required this.descriptorPath,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectInstanceId.hashCode ^
      revision.hashCode ^
      name.hashCode ^
      dirty.hashCode ^
      descriptorPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectView &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectInstanceId == other.projectInstanceId &&
          revision == other.revision &&
          name == other.name &&
          dirty == other.dirty &&
          descriptorPath == other.descriptorPath;
}

class RationalTimeView {
  final PlatformInt64 numerator;
  final int denominator;

  const RationalTimeView({required this.numerator, required this.denominator});

  @override
  int get hashCode => numerator.hashCode ^ denominator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RationalTimeView &&
          runtimeType == other.runtimeType &&
          numerator == other.numerator &&
          denominator == other.denominator;
}

class RecoveryActionResult {
  final bool succeeded;
  final bool changed;
  final String message;

  const RecoveryActionResult({
    required this.succeeded,
    required this.changed,
    required this.message,
  });

  @override
  int get hashCode => succeeded.hashCode ^ changed.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveryActionResult &&
          runtimeType == other.runtimeType &&
          succeeded == other.succeeded &&
          changed == other.changed &&
          message == other.message;
}

class RecoveryInspectionView {
  final String status;
  final String projectId;
  final BigInt baseRevision;
  final BigInt recoveryRevision;
  final String recoveryName;
  final String conflictReason;
  final String message;

  const RecoveryInspectionView({
    required this.status,
    required this.projectId,
    required this.baseRevision,
    required this.recoveryRevision,
    required this.recoveryName,
    required this.conflictReason,
    required this.message,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      projectId.hashCode ^
      baseRevision.hashCode ^
      recoveryRevision.hashCode ^
      recoveryName.hashCode ^
      conflictReason.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveryInspectionView &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          projectId == other.projectId &&
          baseRevision == other.baseRevision &&
          recoveryRevision == other.recoveryRevision &&
          recoveryName == other.recoveryName &&
          conflictReason == other.conflictReason &&
          message == other.message;
}

enum TimelineTrackKindView { video, audio }

enum TimelineTrimEdgeView { start, end }
