[package]
name = "or_core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["raw_value"] }
sha2 = { version = "0.11.0", default-features = false, features = ["alloc"] }
uuid = { version = "1.26.1", features = ["serde", "v4"] }
url = { version = "2.5.8", default-features = false, features = ["std"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }
