name: or_app
description: Opencut Reinforced application shell.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.1.0
  or_app_bridge:
    path: ../../packages/or_app_bridge
  or_viewer_texture:
    path: ../../packages/or_viewer_texture

hooks:
  user_defines:
    or_app_bridge:
      android_ffmpeg_install_root: android/.ffmpeg-install

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
